#%RAML 1.0
title: Keros
uses:
  GeneralTypes: ./types/GeneralTypes.raml
  AuthTypes: ./types/AuthTypes.raml
  GeneralResourceTypes: ./resourceTypes/GeneralResourceTypes.raml
  DocumentResourceTypes: ./resourceTypes/DocumentResourceTypes.raml
  Security: ./securitySchemes/security.raml
  Traits: ./traits/traits.raml

  CoreTypes: ./types/Core/CoreTypes.raml
  CoreRequests: ./types/Core/CoreRequests.raml
  UATypes: ./types/UA/UATypes.raml
  UARequests: ./types/UA/UARequests.raml
  TresoTypes: ./types/Treso/TresoTypes.raml
  TresoRequests: ./types/Treso/TresoRequests.raml
version: v1
baseUri: /api/v1
mediaType:
  - application/json
protocols:
  - HTTP
  - HTTPS
types:
  Error: GeneralTypes.Error
description: This API represents the interface between Keros-Back and Keros-Front. All requests and responses are of JSON type.

/auth:
  description: Authentication endpoints
  /login:
    displayName: Login
    post:
      body: AuthTypes.LoginRequest
      description: Allows the user to log into the platform
      responses:
        200:
          description: Returned when authentication is successful
          body: AuthTypes.LoginResponse
        401:
          description: Returned when authentication failed - because of wrong username or password
          body: GeneralTypes.Error
        500:
          description: Returned for any other error that is not handled
          body: GeneralTypes.Error

/core:
  description: Core endpoints, used at multiple places in the application
  /member:
    type:  { GeneralResourceTypes.GetPage+Create: {item : CoreTypes.Member, itemRequest : CoreRequests.CreateMember } }
    get:
      queryParameters:
        poleId:
          description: If specified, add a search criteria to the users pole
          type: integer
          required: false
        positionId:
          description: If specified, add a search criteria to the users position
          type: integer
          required: false
  /member/me:
    type: { GeneralResourceTypes.ConnectedUser-Get+Update: {item : CoreTypes.Member, itemUpdateRequest : CoreRequests.UpdateMember  } }
  /member/{id}:
    type: { GeneralResourceTypes.Get+Update+Delete: {item : CoreTypes.Member, itemUpdateRequest : CoreRequests.UpdateMember  } }
  /country:
    type:  { GeneralResourceTypes.GetAll: {item : CoreTypes.Country } }
  /country/{id}:
    type:  { GeneralResourceTypes.Get: {item : CoreTypes.Country } }
  /address/{id}:
    type:  { GeneralResourceTypes.Get: {item : CoreTypes.Address } }
  /position:
    type:  { GeneralResourceTypes.GetAll: {item : CoreTypes.Position } }
  /position/{id}:
    type:  { GeneralResourceTypes.Get: {item : CoreTypes.Position } }
  /department:
    type:  { GeneralResourceTypes.GetAll: {item : CoreTypes.Department } }
  /department/{id}:
    type:  { GeneralResourceTypes.Get: {item : CoreTypes.Department } }
  /pole:
    type:  { GeneralResourceTypes.GetAll: {item : CoreTypes.Pole } }
  /pole/{id}:
    type:  { GeneralResourceTypes.Get: {item : CoreTypes.Pole } }
  /gender:
    type:  { GeneralResourceTypes.GetAll: {item : CoreTypes.Gender } }

/ua:
  description: UA endpoints
  /firm-type:
    type:  { GeneralResourceTypes.GetAll: {item : UATypes.FirmType } }
  /firm-type/{id}:
    type: { GeneralResourceTypes.Get: {item : UATypes.FirmType } }
  /firm:
    type:  { GeneralResourceTypes.GetPage+Create: {item : UATypes.Firm, itemRequest : UARequests.CreateFirm } }
  /firm/{id}:
    type: { GeneralResourceTypes.Get+Update+Delete: {item : UATypes.Firm, itemUpdateRequest : UARequests.UpdateFirm  } }
  /contact:
    type:  { GeneralResourceTypes.GetPage+Create: {item : UATypes.Contact, itemRequest : UARequests.CreateContact } }
    get:
      queryParameters:
        firmId:
          description: If specified, add a search criteria to the contacts firm
          type: integer
          required: false
  /contact/{id}:
    type: { GeneralResourceTypes.Get+Update+Delete: {item : UATypes.Contact, itemUpdateRequest : UARequests.UpdateContact  } }
  /status:
    type:  { GeneralResourceTypes.GetAll: {item : UATypes.StudyStatus } }
  /status/{id}:
    type: { GeneralResourceTypes.Get: {item : UATypes.StudyStatus } }
  /provenance:
    type:  { GeneralResourceTypes.GetAll: {item : UATypes.StudyProvenance } }
  /provenance/{id}:
    type: { GeneralResourceTypes.Get: {item : UATypes.StudyProvenance } }
  /field:
    type:  { GeneralResourceTypes.GetAll: {item : UATypes.StudyField } }
  /field/{id}:
    type: { GeneralResourceTypes.Get: {item : UATypes.StudyField } }
  /study:
    type:  { GeneralResourceTypes.GetPage+Create: {item : UATypes.Study, itemRequest : UARequests.CreateStudy } }
  /study/me:
    type:  { GeneralResourceTypes.GetPage: {item : UATypes.Study } }
  /study/{id}:
    type: { GeneralResourceTypes.Get+Update+Delete: {item : UATypes.Study, itemUpdateRequest : UARequests.UpdateStudy  } }
  /study/{studyId}/documents:
    get:
      is: [Traits.hasCommonError]
      description: Gets the document information pertaining to the study
      securedBy:
        - Security.OAuth2-0
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                documents:
                  type: array
                  items:
                    type: object
                    properties: 
                      id: number
                      name: 
                        type: string
                        description: The display name of the documents
                      generateLocation:
                        type: string
                        description: The URI to call to generate the template and get a secret location
                      uploadLocation:
                        type: string
                        description: The URL to call to upload the document in it's final version
                      downloadLocation:
                        type: string
                        description: The URL to call to download the document in it's final version
              example: 
                {
                  "documents": [
                    {
                      "id": 1,
                      "name": "Contrat de confidentialité",
                      "generateLocation": "http://keros-api-dev.etic-insa.com/api/v1/ua/study/5/template/1",
                      "uploadLocation": "http://keros-api-dev.etic-insa.com/api/v1/ua/study/5/document/1",
                      "downloadLocation": "http://keros-api-dev.etic-insa.com/api/v1/ua/study/5/document/1"
                    }
                  ]
                }
  /study/{studyId}/template/{templateId}:
    get:
      is: [Traits.hasCommonError]
      description: Asks for the template to be filled in with data from the study and returns the secret location of the file
      securedBy:
        - Security.OAuth2-0
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                location:
                  type: string
                  description: The secret location of the generated template - the user should be redirected here
              example:
                {
                  "location": "http://keros-api-dev.etic-insa.com/api/v1/core/document/a946092b-7387-4f42-bcd0-d4e43ccab89e"
                }
  /study/{studyId}/document/{documentId}:
    post:
      is: [Traits.hasCommonError]
      description: Uploads a document in it's final version once verified by UA. If it already exists it must be replaced
      securedBy:
        - Security.OAuth2-0
      responses:
        200:
          description: Document is correctly uploaded
    get:
      is: [Traits.hasCommonError]
      description: Downloads a document in it's final version once verified by UA
      securedBy:
        - Security.OAuth2-0
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                location:
                  type: string
                  description: The secret location of the document - the user should be redirected here
              example:
                {
                  "location": "http://keros-api-dev.etic-insa.com/api/v1/core/document/a946092b-7387-4f42-bcd0-d4e43ccab89e"
                }

/treso:
  description: Tréso endpoints
  /facture-types:
    type:  { GeneralResourceTypes.GetAll: {item : TresoTypes.FactureType } }
  /facture:
    type:  { GeneralResourceTypes.GetPage+Create: {item : TresoTypes.Facture, itemRequest : TresoRequests.CreateFacture } }
  /facture/{id}:
    type: { GeneralResourceTypes.Get+Update+Delete: {item : TresoTypes.Facture, itemUpdateRequest : TresoRequests.CreateFacture  } }
