#%RAML 1.0 Library
types:
  LoginRequest:
    type: object
    description: Typical login request
    properties:
      username: string
      password:
        type: string
    example:
      {
        "username": "thomasD",
        "password": "foobar"
      }

  LoginResponse:
    type: object
    description: Contains the OAuth2.0 authentication token
    properties:
      token: string
    example:
      {
        "token": "thomasD"
      }
