#%RAML 1.0 Library
types:
  Error:
    type: object
    properties:
      status: number
      message: string
    example:
      {
        "status": 500,
        "message": "Internal Service Error"
      }
