#%RAML 1.0 Library
uses:
  UATypes: ./UATypes.raml
  CoreTypes: ../Core/CoreTypes.raml
types:
  CreateFirm:
    type: object
    description: Represents a firm creation request.
    properties:
      siret:
        type: UATypes.Siret
        required: false
      name:
        type: string
      address: CoreTypes.Address
      typeId:
        type: number
        description: The ID of the firm's type

  UpdateFirm:
    type: object
    description: Represents a firm update request. Any or none of the fields can be present.
    properties:
      siret:
        type: UATypes.Siret
        required: false
      name:
        type: string
      address: CoreTypes.Address
      typeId:
        type: number
        description: The ID of the firm's type
      
  CreateContact:
    type: object
    description: Represents a contact creation request. Basically a contact object without server defined info.
    properties:
      firstName: string
      lastName: string
      genderId: number
      firmId: number
      email: string
      telephone:
        type: string
        required: false
      cellphone:
        type: string
        required: false
      position:
        type: string
        required: false
      notes:
        type: string
        required: false
      old:
        type: boolean
        required: false
        default: false

  UpdateContact:
    type: object
    description: Represents a contact update request. Any none present fields is like deleting the field
    properties:
      firstName: string
      lastName: string
      genderId: number
      firmId: number
      email: string
      telephone:
        type: string
        required: false
      cellphone:
        type: string
        required: false
      position:
        type: string
        required: false
      notes:
        type: string
        required: false
      old:
        type: boolean
        required: false
        default: false

  CreateStudy:
    type: object
    description: Represents a study creation request. Basically a study object without server defined info.
    properties:
      id:
        type: number
      projectNumber:
        type: number
      name:
        type: string
      description:
        type: string
      fieldId:
        type: number
      provenanceId:
        type: number
        required: false
      statusId:
        type: number
      signDate:
        type: date-only
        required: false
      endDate:
        type: date-only
        required: false
      managementFee:
        type: CoreTypes.Money
        required: false
      realizationFee:
        type: CoreTypes.Money
        required: false
      rebilledFee:
        type: CoreTypes.Money
        required: false
      ecoparticipationFee:
        type: CoreTypes.Money
        required: false
      outsourcingFee:
        type: CoreTypes.Money
        required: false
      archivedDate:
        type: date-only
        required: false
      firmId:
        type: number
      contactIds:
        type: array
        items: number
        minItems: 1
      leaderIds:
        type: array
        items: number
        minItems: 1
        maxItems: 3
      consultantIds:
        type: array
        items: number
        minItems: 1
      qualityManagerIds:
        type: array
        items: number
        minItems: 1
        maxItems: 3

  UpdateStudy:
    type: object
    description: Represents a Study update request. Any none present fields is like deleting the field
    properties:
      id:
        type: number
      projectNumber:
        type: number
      name:
        type: string
      description:
        type: string
      fieldId:
        type: number
      provenanceId:
        type: number
        required: false
      statusId:
        type: number
      signDate:
        type: date-only
        required: false
      endDate:
        type: date-only
        required: false
      managementFee:
        type: CoreTypes.Money
        required: false
      realizationFee:
        type: CoreTypes.Money
        required: false
      rebilledFee:
        type: CoreTypes.Money
        required: false
      ecoparticipationFee:
        type: CoreTypes.Money
        required: false
      outsourcingFee:
        type: CoreTypes.Money
        required: false
      archivedDate:
        type: date-only
        required: false
      firmId:
        type: number
      contactIds:
        type: array
        items: number
        minItems: 1
      leaderIds:
        type: array
        items: number
        minItems: 1
        maxItems: 3
      consultantIds:
        type: array
        items: number
        minItems: 1
      qualityManagerIds:
        type: array
        items: number
        minItems: 1
        maxItems: 3
