#%RAML 1.0 Library
uses:
  CoreTypes: ../Core/CoreTypes.raml
types:
  FirmType:
    type: object
    description: A type of firm
    properties:
      id: number
      label: string
    example:
      {
        id: 1,
        label: "PME/PMI"
      }
    
  Siret:
    type: string
    maxLength: 20
    description: A company's SIRET

  Firm:
    type: object
    description: A firm / company that ETIC is associated with (clients, partners, etc)
    properties:
      id: number
      siret:
        type: Siret
        required: false
      name:
        type: string
        description: The company's name, or the persons name if it is a physical person
      address: CoreTypes.Address
      type: FirmType
    example:
      {
        id: 1,
        siret: "544683216546",
        name: "Cool Company Inc.",
        address: {
          id: 1,
          line1: "13 rue du renard",
          line2: "appt 421",
          city: "Villeurbanne",
          postalCode: "69100",
          country: {
            id: 5,
            label: "France"
          }
        },
        type: {
          id: 1,
          label: "PME/PMI"
        }
      }

  Contact:
    type: object
    description: A contact from a client firm
    properties:
      id: number
      firstName: string
      lastName: string
      gender: CoreTypes.Gender
      firm: Firm
      email: string
      telephone:
        type: string
        required: false
        description: A contacts home or work phone number
      cellphone:
        type: string
        required: false
        description: A contacts cellphone number
      position:
        type: string
        required: false
        description: The contacts position / job within his firm
      notes:
        type: string
        required: false
        description: Various notes about the contact if needed (mostly will be empty)
      old:
        type: boolean
        description: Whether the contact is still active today
    example:
      {
        id: 1,
        firstName: "Thomas",
        lastName: "Edison",
        gender: {
          id: 2,
          label: "F"
        },
        firm: {
          id: 1,
          siret: "544683216546",
          name: "Cool Company Inc.",
          address: {
            id: 1,
            line1: "13 rue du renard",
            line2: "appt 421",
            city: "Villeurbanne",
            postalCode: "69100",
            country: {
              id: 5,
              label: "France"
            }
          },
          type: {
            id: 1,
            label: "PME/PMI"
          }
        },
        email: "thomas.edison@nomail.com",
        telephone: "0033575489521",
        cellphone: "0033675445501",
        position: "Directeur de commerce",
        notes: "A contacter en premier pour l'entreprise Nofirm",
        old: false
      }

  ContactShort:
    type: object
    description: A shorter version of Contact
    properties:
      id: number
      firstName: string
      lastName: string
      gender: CoreTypes.Gender
      email: string
      telephone:
        type: string
        required: false
        description: A contacts home or work phone number
      cellphone:
        type: string
        required: false
        description: A contacts cellphone number
      position:
        type: string
        required: false
        description: The contacts position / job within his firm
    example:
      {
        id: 1,
        firstName: "Thomas",
        lastName: "Edison",
        gender: {
          id: 2,
          label: "F"
        },
        email: "thomas.edison@nomail.com",
        telephone: "0033575489521",
        cellphone: "0033675445501",
        position: "Directeur de commerce"
      }
  
  StudyStatus:
    type: object
    description: A status of a specific study
    properties:
      id: number
      label: string
    example:
      {
        id: 1,
        label: "En cours"
      }

  StudyField:
    type: object
    properties:
      id: number
      label: string
    example:
      {
        id: 2,
        label: "Web"
      }

  StudyProvenance:
    type: object
    properties:
      id: number
      label: string
    example:
      {
        id: 4,
        label: "Phoning"
      }


  Study:
    type: object
    description: A study (could also be called a project) with all associated business information
    properties:
      id:
        type: number
        required: true
      projectNumber:
        type: number
        description: The real life number associated with this project. In other words, the project number used on physical papers
      name:
        type: string
      description:
        type: string
      field:
        type: StudyField
      status:
        type: StudyStatus
      provenance:
        type: StudyProvenance
      signDate:
        type: date-only
      endDate:
        type: date-only
        required: false
      managementFee:
        type: CoreTypes.Money
        required: false
      realizationFee:
        type: CoreTypes.Money
        required: false
      rebilledFee:
        type: CoreTypes.Money
        required: false
      ecoparticipationFee:
        type: CoreTypes.Money
        required: false
      outsourcingFee:
        type: CoreTypes.Money
        required: false
      archivedDate:
        type: date-only
        required: false
        description: If the project is archived, this date speciifies when that happened. If not, will be either null or not present.
      firm:
        type: Firm
      contacts:
        type: array
        items: ContactShort
        description: An array containing all contacts associated with this project
        minItems: 1
      leaders:
        type: array
        items: CoreTypes.MemberShort
        description: An array containing the projet leads within ETIC INSA Technologies
        minItems: 1
        maxItems: 3
      consultants:
        type: array
        items: CoreTypes.MemberShort
        description: An array containing all members working as consultants for the project
        minItems: 1
      qualityManagers:
        type: array
        items: CoreTypes.MemberShort
        description: An array containing one or two members of ETIC who ensure quality control
        minItems: 1
        maxItems: 3
    example:
      {
        id: 1,
        projectNumber: 4125,
        name: "Création d'un site internet",
        description: "Le site web est un magasin en ligne",
        field: {
          id: 7,
          label: "Web"
        },
        status: {
          id: 1,
          label: "En cours"
        },
        provenance: {
          id: 1,
          label: "Phoning"
        },
        signDate: "2018-11-20",
        endDate: "2019-12-01",
        managementFee: 112,
        realizationFee: 174,
        rebilledFee: 25,
        ecoparticipationFee: 100,
        outsourcingFee: 45,
        archivedDate: "2020-01-02",
        firm: {
          id: 1,
          siret: "544683216546",
          name: "Cool Company Inc.",
          address: {
            id: 1,
            line1: "13 rue du renard",
            line2: "appt 421",
            city: "Villeurbanne",
            postalCode: "69100",
            country: {
              id: 5,
              label: "France"
            }
          },
          type: {
            id: 1,
            label: "PME/PMI"
          }
        },
        contacts: [
          {
            id: 1,
            firstName: "Thomas",
            lastName: "Edison",
            gender: {
              id: 2,
              label: "F"
            },
            email: "thomas.edison@nomail.com",
            telephone: "0033575489521",
            cellphone: "0033675445501",
            position: "Directeur de commerce"
          }
        ],
        leaders: [
          {
            id: 1,
            username: "clion",
            firstName: "charlène",
            lastName: "lion",
            gender: {
                id: 2,
                label: "F"
            }
          }
        ],
        consultants: [
          {
            id: 1,
            username: "clion",
            firstName: "charlène",
            lastName: "lion",
            gender: {
                id: 2,
                label: "F"
            }
          }
        ],
        qualityManagers: [
          {
            id: 1,
            username: "clion",
            firstName: "charlène",
            lastName: "lion",
            gender: {
                id: 2,
                label: "F"
            }
          }
        ]
      }
  
      
