#%RAML 1.0 Library
types:
  FirmType:
    type: object
    description: A type of firm
    properties:
      id: number
      label: string
    example:
      {
        id: 1,
        label: "PME/PMI",
      }

  Siret:
    type: string
    maxLength: 20
    description: A companie's SIRET

  Firm:
    type: object
    description: A firm / company that ETIC is associated with (clients, partners, etc)
    properties:
      id: number
      siret:
        type: Siret
        required: false
      name:
        type: string
        description: The companie's name, or the persons name if it is a physical person
      addressId: number
      typeId:
        type: number
        description: The ID of the firm's type
    example:
      {
        id: 1,
        siret: "544683216546",
        name: "Cool Company Inc.",
        addressId: 5,
        typeId: 2
      }

  Contact:
    type: object
    description: A contact from a client firm
    properties:
      id: number
      firstName: string
      lastName: string
      genderId: number
      firmId: number
      email: string
      telephone:
        type: string
        required: false
        description: A contacts home or work phone number
      cellphone:
        type: string
        required: false
        description: A contacts cellphone number
      position:
        type: string
        required: false
        description: The contacts position / job within his firm
      notes:
        type: string
        required: false
        description: Various notes about the contact if needed (mostly will be empty)
      old:
        type: boolean
        description: Whether the contact is still active today
