#%RAML 1.0 Library
uses:
  CoreTypes: ../Core/CoreTypes.raml
  CoreRequests: ../Core/CoreRequests.raml
  UATypes: ../UA/UATypes.raml
  TresoTypes: ./TresoTypes.raml
types:
  FactureRequest:
    type: object
    description: Une demande de création de facture
    properties:
      numero:
        type: string
        description: Un string saisie par les utilisateurs sans valeur technique
        minLength: 5
        maxLength: 32
        required: false
      fullAddress:
        type: CoreRequests.AddressRequest
        description: L'addresse qui apparait sur la facture. Par défaut l'addresse de l'entreprise
        required: false
      clientName: 
        type: string
        description: Le nom du clientName. Par défaut le nom de l'entreprise
        required: false
      contactName:
        type: string
        description: Nom de la personne à qui est addressée la facture. Par défaut le nom du contact principal du firm.
        required: false
      contactEmail:
        type: string
        description: Nom de la personne à qui est addressée la facture. Par défaut l'email du contact principal du firm.
        required: false
      studyId:
        type: number
        description: "L'étude concernée par la facture (contenant les informations comme l'entreprise, le sujet de la facture, ...)"
        required: true
      type:
        type: TresoTypes.FactureType
        required: true
      amountDescription:
        type: string
        example: D’un montant de quatre mille quatre-vingt euros toutes taxes comprises (4080€ TTC), correspondant à la réalisation de 13 JEH
        description: L'objet de la facture saisie par les utilisateurs (copié d'un document existant généralement)
        minLength: 1
        maxLength: 2048
        required: false
      subject:
        type: string
        example: "réalisation d’une plateforme d’optimisation logistique"
        description: Ce qui est facturé. Par défaut le nom du study
        required: false
      agreementSignDate:
        type: date-only
        description: date à laquelle la convention a été signée. Par défaut Study.signDate
        required: false
      amountHT:
        type: CoreTypes.Money
        description: Montant hors taxe facturé
        required: false
      taxPercentage:
        type: number
        description: Le pourcentage de TVA à appliquer (nombre flottant)
        example: 20.5
        default: 20.0
        required: false
      dueDate:
        type: date-only
        description: Date d'écheance de la facture
        required: false
      additionalInformation:
        type: string
        description: Infos additionnelles saisies par n'importe qui qui a le droit d'éditer
        required: false

  BulletinVersementRequest:
    type: object
    description: Une demande de création ou de modification de bulletin de versement
    properties:
      missionRecapNumber:
        type: string
        description: Un string saisie par les utilisateurs sans valeur technique représentant le numéro de Récapitulatif Mission (le doc qui lie le consultant à ETIC)
        minLength: 5
        maxLength: 32
        required: false
      consultantName:
        type: string
        description: Le nom/prénom du consultant. Par défaut le nom/prénom du consultant. Exemple - LOREM Ipsum-Nawa
        required: false
      consultantSocialSecurityNumber:
        type: string
        description: Le numéro de sécurité sociale du consultant. Saisie par l'utilisateur
        required: false
      address:
        type: CoreRequests.AddressRequest
        description: Addresse du consultant. Par défaut l'addresse du membre représentant le consultant.
        required: false
      email:
        type: string
        description: l'email du consultant. Par défaut l'email du membre
        required: false
      studyId:
        type: number
        description: L'étude pour laquelle le versement doit avoir lieu
      consultantId:
        type: number
        description: Le consultant concerné
      clientName:
        type: string
        description: Nom du client de l'étude. Par défaut le nom du firm associé à l'étude
        required: false
      projectLead:
        type: string
        description: Nom/prénom du chargé d'affaires de l'étude. Modifiable donc stocké sous forme de string. Exemple - LOREM Ipsum-Nawa
        required: false
      isTotalJeh:
        type: boolean
        description: Vrai si le nombre de JEH spécifié représente le nombre total de JEH du consultant pour cette étude.
        required: false
      isStudyPaid:
        type: boolean
        description: Vrai si l’étude a été payée en totalité par le client.
        required: false
      amountDescription:
        type: string
        example: D’un montant de quatre mille quatre-vingt euros toutes taxes comprises (4080€ TTC), correspondant à la réalisation de 13 JEH
        description: L'objet de la facture saisie par les utilisateurs (copié d'un document existant généralement)
        minLength: 1
        maxLength: 2048
        required: false