#%RAML 1.0 Library
types:
  Money:
    type: number
    description: Represents a specific amount of money in euros (€)

  Gender:
    type: object
    properties:
      id: number
      label:
        minLength: 1
        maxLength: 1
        type: string
        enum:
          - H
          - F
          - A
          - I
    description: Gender of the user, with A being "Autre" and I being "Inconnu".

  Department:
    type: object
    description: A INSA Lyon school department
    properties:
      id: number
      label:
        type: string
        description: A short acryonym for the department
      name:
        type: string
        description: The full name of the department
    example:
      {
        id: 7,
        label: "TC",
        name: "Télécommunications, Services & Usages"
      }

  Country:
    type: object
    description: A country
    properties:
      id: number
      label: string
    example:
      {
        id: 5,
        label: "France"
      }

  SchoolYear:
    type: number
    description: A INSA Lyon school year
    enum:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8

  Pole:
    type: object
    description: A pole within ETIC INSA Technologies
    properties:
      id: number
      label:
        type: string
        description: A short abbreviation the the name
      name:
        type: string
        description: The full name of the pole
    example:
      {
        id: 1,
        label: "Com",
        name: "Communication"
      }

  Position:
    type: object
    description: A member's position with ETIC INSA Technologies (or other position like client)
    properties:
      id: number
      label: string
      poleId:
        type: number
        description: The ID of the member's pole. If not a ETIC position, then it's null (ex client)
        required: false
    example:
      {
        id: 1,
        label: "Président(e)",
        poleId: 5
      }

  Address:
    type: object
    properties:
      line1: string
      line2:
        type: string
        required: false
      city: string
      postalCode: string
      countryId: number

  Member:
    type: object
    description: Reprensents a Keros user and a Member of ETIC INSA Technologies
    properties:
      id: number
      username: string
      firstName: string
      lastName: string
      genderId: number
      email: string
      birthday:
        type: date-only
        description: No time, only a date of format YYYY-MM-DD
      departmentId:
        type: number
        required: false
        description: the ID of the member's school department
      schoolYear:
        type: SchoolYear
        required: false
      telephone:
        type: string
        required: false
      addressId: number
      positionIds:
        type: array
        items: number
        required: true
        description: The ID of the member's position(s) within ETIC INSA Technologies. Can have from 1 to N items.
    example:
      {
        id: 5,
        username: "jconnor",
        firstName: "John",
        lastName: "Connor",
        genderId: 5,
        email: "john.conor@terminator.com",
        birthday: "1967-01-20",
        departmentId: 5,
        schoolYear: 3,
        telephone: "0033675489521",
        addressId: 7,
        positionIds: [4, 6]
      }

  MemberShort:
    type: object
    description: Is a smaller and more compact version of Member
    properties:
      id: number
      username: string
      firstName: string
      lastName: string
      gender: Gender