#%RAML 1.0 Library
types:
  Money:
    type: number
    description: Represents a specific amount of money in euros (€)

  Gender:
    type: object
    properties:
      id: number
      label:
        minLength: 1
        maxLength: 1
        type: string
        enum:
          - H
          - F
          - A
          - I
    description: Gender of the user, with A being "Autre" and I being "Inconnu".
    example:
      {
        id: 2,
        label: "H",
      }

  Department:
    type: object
    description: A INSA Lyon school department
    properties:
      id: number
      label:
        type: string
        description: A short acryonym for the department
      name:
        type: string
        description: The full name of the department
    example:
      {
        id: 7,
        label: "TC",
        name: "Télécommunications, Services & Usages"
      }

  Country:
    type: object
    description: A country
    properties:
      id: number
      label: string
    example:
      {
        id: 5,
        label: "France"
      }

  SchoolYear:
    type: number
    description: A INSA Lyon school year
    enum:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8

  Pole:
    type: object
    description: A pole within ETIC INSA Technologies
    properties:
      id: number
      label:
        type: string
        description: A short abbreviation the the name
      name:
        type: string
        description: The full name of the pole
    example:
      {
        id: 1,
        label: "Com",
        name: "Communication"
      }

  Position:
    type: object
    description: A member's position with ETIC INSA Technologies (or other position like client)
    properties:
      id: number
      label: string
      pole:
        type: Pole
        required: false
    example:
      {
        id: 1,
        label: "Président(e)",
        pole: {
          id: 1,
          label: "Com",
          name: "Communication"
        }
      }

  Address:
    type: object
    properties:
      id: number
      line1: string
      line2:
        type: string
        required: false
      city: string
      postalCode: string
      country: Country
    example:
      {
        id: 1,
        line1: "13 rue du renard",
        line2: "appt 421",
        city: "Villeurbanne",
        postalCode: "69100",
        country: {
          id: 5,
          label: "France"
        }
      }

  Member:
    type: object
    description: Reprensents a Keros user and a Member of ETIC INSA Technologies
    properties:
      id: number
      username: string
      firstName: string
      lastName: string
      gender: Gender
      email: string
      birthday:
        type: date-only
        description: No time, only a date of format YYYY-MM-DD
      department:
        type: Department
        required: false
        description: the ID of the member's school department
      schoolYear:
        type: SchoolYear
        required: false
      telephone:
        type: string
        required: false
      address: Address
      positions:
        type: array
        items: Position
        required: true
        description: The member's position(s) within ETIC INSA Technologies. Can have from 1 to N items.
    example:
      {
        id: 5,
        username: "jconnor",
        firstName: "John",
        lastName: "Connor",
        gender: {
          id: 2,
          label: "H",
        },
        email: "john.conor@terminator.com",
        birthday: "1967-01-20",
        department: {
          id: 7,
          label: "TC",
          name: "Télécommunications, Services & Usages"
        },
        schoolYear: 3,
        telephone: "0033675489521",
        address: {
          id: 1,
          line1: "13 rue du renard",
          line2: "appt 421",
          city: "Villeurbanne",
          postalCode: "69100",
          country: {
            id: 5,
            label: "France"
          }
        },
        positions: [
          {
            id: 1,
            label: "Président(e)",
            pole: {
              id: 1,
              label: "Com",
              name: "Communication"
            }
          }
        ]
      }

  MemberShort:
    type: object
    description: Is a smaller and more compact version of Member
    properties:
      id: number
      username: string
      firstName: string
      lastName: string
      gender: Gender