#%RAML 1.0 Library
uses:
  CoreTypes: ./CoreTypes.raml
types:
  PositionRequest:
    type: object
    description: A tuple of position ID and linked information
    properties: 
      id: number
      year: number
      isBoard: boolean

  CreateMember:
    type: object
    description: Represents a member creation request. Basically a Member object without server defined info.
    properties:
      username: string
      password: string
      firstName: string
      lastName: string
      genderId: number
      email: string
      birthday:
        type: date-only
        description: No time, only a date of format YYYY-MM-DD
      departmentId:
        type: number
        required: false
      schoolYear:
        type: CoreTypes.SchoolYear
        required: false
      telephone:
        type: string
        required: false
      address: CoreTypes.Address
      positions:
        type: array
        items: PositionRequest
        required: true
        description: The member's position(s) within ETIC INSA Technologies. Can have from 1 to N items.

  UpdateMember:
    type: object
    description: Represents a member update request. Any none present fields is like deleting the field
    properties:
      username: string
      password:
        type: string
        required: false
      firstName: string
      lastName: string
      genderId: number
      email: string
      birthday:
        type: date-only
        description: No time, only a date of format YYYY-MM-DD
      departmentId:
        type: number
        required: false
      schoolYear:
        type: CoreTypes.SchoolYear
        required: false
      telephone:
        type: string
        required: false
      address: CoreTypes.Address
      positions:
        type: array
        items: PositionRequest
        required: true
        description: The member's position(s) within ETIC INSA Technologies. Can have from 1 to N items.
